// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCey0it7KjKzSDzXy21dX7mRLN_xdOvX6Y',
    appId: '1:490755196622:web:132250b07a3dda37ea729f',
    messagingSenderId: '490755196622',
    projectId: 'weather-a4e99',
    authDomain: 'weather-a4e99.firebaseapp.com',
    storageBucket: 'weather-a4e99.appspot.com',
    measurementId: 'G-EMGK6GRT4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvbdzhoGM6Av_Mca1kAG0u0YB6djQFyZU',
    appId: '1:490755196622:android:b3468beac1993223ea729f',
    messagingSenderId: '490755196622',
    projectId: 'weather-a4e99',
    storageBucket: 'weather-a4e99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogJkVT7-1hQoT2LwDTN_mvT5OjR4e9n0',
    appId: '1:490755196622:ios:ccd297fcce630afeea729f',
    messagingSenderId: '490755196622',
    projectId: 'weather-a4e99',
    storageBucket: 'weather-a4e99.appspot.com',
    iosBundleId: 'com.example.weatherTennisAiModel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogJkVT7-1hQoT2LwDTN_mvT5OjR4e9n0',
    appId: '1:490755196622:ios:ccd297fcce630afeea729f',
    messagingSenderId: '490755196622',
    projectId: 'weather-a4e99',
    storageBucket: 'weather-a4e99.appspot.com',
    iosBundleId: 'com.example.weatherTennisAiModel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCey0it7KjKzSDzXy21dX7mRLN_xdOvX6Y',
    appId: '1:490755196622:web:ec0f52dda17df6a7ea729f',
    messagingSenderId: '490755196622',
    projectId: 'weather-a4e99',
    authDomain: 'weather-a4e99.firebaseapp.com',
    storageBucket: 'weather-a4e99.appspot.com',
    measurementId: 'G-738VY05Z4E',
  );
}
